version: '3.8'

services:
  goat:
    build:
      context: .
      target: dev
    environment:
      - PORT=80
      - ENV=local
    volumes:
      - ./:/code
      - cache:/root/.cache
    image: goat:dev
    ports:
      - 9000:80

volumes:
  cache: {}
